# Generated by Django 5.2.17 on 2026-08-24 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash_sales/%Y/%m/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(blank=True, help_text='Empty means global flash sale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='logistics.darkstore')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_allocated', models.PositiveIntegerField(default=100)),
                ('stock_sold', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_sale_items', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/')),
                ('target_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('flash_sale', 'Flash Sale'), ('external', 'External URL')], default='product', max_length=20)),
                ('target_id', models.CharField(blank=True, help_text='Product ID, Category ID, Flash Sale ID or external URL.', max_length=100)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(blank=True, help_text='Empty means this banner is global. Otherwise it belongs to this dark store.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='logistics.darkstore')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['dark_store', 'is_active'], name='promotions__dark_st_4cef3a_idx'), models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_df3d18_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['dark_store', 'is_active'], name='promotions__dark_st_50fa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['start_time', 'end_time'], name='promotions__start_t_29a474_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleitem',
            index=models.Index(fields=['flash_sale', 'is_active'], name='promotions__flash_s_0344b5_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleitem',
            index=models.Index(fields=['product', 'is_active'], name='promotions__product_7e2512_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashsaleitem',
            constraint=models.UniqueConstraint(fields=('flash_sale', 'product'), name='unique_product_per_flash_sale'),
        ),
    ]
