# Generated by Django 5.2.17 on 2026-08-24 10:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('gateway', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('sslcommerz', 'SSLCommerz'), ('cod', 'Cash on Delivery')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'), models.Index(fields=['user', 'status'], name='payments_pa_user_id_92d873_idx'), models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_186290_idx'), models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx'), models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_d79ddc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_gte_zero'), models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='refunded_amount_gte_zero')],
            },
        ),
    ]
