# Generated by Django 5.2.17 on 2026-08-24 10:02

from logistics.gis_compat import gis_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('location', gis_models.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='logistics.darkstore')),
            ],
            options={
                'ordering': ['dark_store', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', gis_models.PolygonField(geography=True, srid=4326)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='logistics.darkstore')),
            ],
            options={
                'ordering': ['dark_store', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('street_address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location', gis_models.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Routing'), ('assigned', 'Assigned to Dark Store'), ('packing', 'Packing at Dark Store'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='logistics.darkstore')),
                ('rider', models.ForeignKey(blank=True, limit_choices_to={'role': 'RIDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_delivery_orders', to=settings.AUTH_USER_MODEL)),
                ('saved_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='logistics.deliveryslot')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='logistics.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='darkstore',
            name='service_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dark_stores', to='logistics.servicearea'),
        ),
        migrations.CreateModel(
            name='DarkStoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='logistics.darkstore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_dark_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dark_store', 'user'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='logistics_d_user_id_54e5cf_idx'), models.Index(fields=['dark_store', 'is_active'], name='logistics_d_dark_st_6ebf2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('dark_store', 'user'), name='unique_dark_store_manager')],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryslot',
            index=models.Index(fields=['dark_store', 'is_active'], name='logistics_d_dark_st_a521b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='delivery_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['dark_store', 'is_active'], name='logistics_d_dark_st_99fd21_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(fields=('dark_store', 'name'), name='unique_delivery_zone_per_store'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['user', 'status'], name='logistics_d_user_id_e782e1_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['dark_store', 'status'], name='logistics_d_dark_st_74ad46_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['delivery_zone', 'status'], name='logistics_d_deliver_8a8045_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['rider', 'status'], name='logistics_d_rider_i_fd04fa_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['created_at'], name='logistics_d_created_5fe2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='darkstore',
            index=models.Index(fields=['service_area', 'is_active'], name='logistics_d_service_a21f22_idx'),
        ),
        migrations.AddIndex(
            model_name='darkstore',
            index=models.Index(fields=['code'], name='logistics_d_code_15c255_idx'),
        ),
    ]
