# Generated by Django 5.2.17 on 2026-08-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('logistics', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductsales',
            name='dark_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_sales', to='logistics.darkstore'),
        ),
        migrations.AddField(
            model_name='dailyproductsales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='products.product'),
        ),
        migrations.AddField(
            model_name='dailysalessummary',
            name='dark_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_summaries', to='logistics.darkstore'),
        ),
        migrations.AddField(
            model_name='productsalesmetric',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_metric', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsales',
            index=models.Index(fields=['date', 'dark_store'], name='analytics_d_date_6407f8_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsales',
            index=models.Index(fields=['date', 'product'], name='analytics_d_date_1c5927_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsales',
            index=models.Index(fields=['dark_store', 'product'], name='analytics_d_dark_st_52afe6_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductsales',
            constraint=models.UniqueConstraint(fields=('date', 'dark_store', 'product'), name='unique_daily_product_store_sales'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['dark_store', '-date'], name='analytics_d_dark_st_69b5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['date', 'dark_store'], name='analytics_d_date_1cabf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysalessummary',
            constraint=models.UniqueConstraint(fields=('date', 'dark_store'), name='unique_daily_sales_per_store'),
        ),
    ]
