# Generated by Django 5.2.17 on 2026-08-24 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlatformConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='BanglaMart', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Disable customer checkout during maintenance.')),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=30.0, max_digits=8)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('support_phone', models.CharField(default='+8801700000000', max_length=20)),
                ('support_email', models.EmailField(default='support@banglamart.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Example: ENABLE_BKASH_PAYMENT', max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
