# Generated by Django 5.2.17 on 2026-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Delivery Rider'), ('warehouse_staff', 'Warehouse Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
