# Generated by Django 5.2.17 on 2026-08-24 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted by Rider'), ('picked_up', 'Picked Up from Dark Store'), ('arrived', 'Arrived at Destination'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_tasks', to='logistics.darkstore')),
                ('delivery_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_task', to='logistics.deliveryorder')),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'RIDER'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', 'status'], name='riders_deli_rider_i_8b12c3_idx'), models.Index(fields=['dark_store', 'status'], name='riders_deli_dark_st_4df889_idx'), models.Index(fields=['status'], name='riders_deli_status_84b7c0_idx'), models.Index(fields=['assigned_at'], name='riders_deli_assigne_d181f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(default='Bicycle', help_text='Example: Bicycle, Bike, Scooter', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_on_duty', models.BooleanField(db_index=True, default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_profiles', to='logistics.darkstore')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dark_store', 'is_available', 'is_on_duty'], name='riders_ride_dark_st_8563c4_idx'), models.Index(fields=['dark_store', 'is_on_duty'], name='riders_ride_dark_st_65d139_idx')],
            },
        ),
    ]
