# Generated by Django 5.2.17 on 2026-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_guestcart_guestcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcart',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestcart',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestcart',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestcart',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
